### ISSUE TITLE
Contentful Gatsby CLI starter

### ISSUE THREAD

**Issue by stefanjudis** [contentful-userland/project-requests#1]
[Gatsby](https://www.gatsbyjs.org/) looks like a pretty neat project these days. It ships with React, GraphQL and a CLI tool.

I think it'd be cool to have a nice contentful [cli starter](https://www.gatsbyjs.org/docs/gatsby-starters/) to get gatsby projects running quicker. :)

This way setting up a new Gatsby/Contentful project would only be

```
gatsby new ./my-new-site https://github.com/contentful-userland/gatsby-starter.git
```

Is anyone up for working with me on that? 😊

**Comment by aderaaij** [comment]
Great initiative. I'm down! Do you have a sort of road map or ideas for a feature set you'd like to implement? Or would you like us to start spit-balling to get some ideas rolling?

**Comment by stefanjudis** [comment]
> Do you have a sort of road map or ideas for a feature set you'd like to implement?

No roadmap and I still have to dig the starter a bit. :)

> Or would you like us to start spit-balling to get some ideas rolling?

I think the best approach would be to create a repo here in `userland` and bounce ideas there? :)
And then lets see how it goes?

And just in case you haven't read it – `Userland` follows [openopensource.org governance](http://openopensource.org/). :)

**Comment by mattbag** [comment]
Hey I already studied a bit the contentful starter, portfolio style, so I'll try to provide any input I can.

I'd say the first goal would be to showcase good/best/advanced features of both gatsby and contentful, to me:
- languages/locales
- gatsby offline/manifest and everything to get pwa
- some client side features
- page transitions
- some elaborated content
- gatsby-image for everything
- some very lightweight css framework? also purify-css is available
+ all the above to stitch some small e-comm? If anyone is familiar with payment apis we can leverage?

Looking forward to read other ideas!

**Comment by axe312ger** [comment]
I'd add the ability to preview your content via the Contentful preview api

**Comment by stefanjudis** [comment]
Hey folks. I created the repo for it. 

https://github.com/contentful-userland/gatsby-contentful-starter

I think we should take it from there then. :)
